server:
  port: 8081

spring:
  application:
    name: scrapper
  grpc:
    server:
      port: 9091

  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    jpa:
      hibernate:
        ddl-auto: validate
      open-in-view: false
      properties:
        hibernate:
          format_sql: true

    flyway:
      enabled: true
      locations: filesystem:./migrations


bot:
  transport: grpc

scheduler:
  interval: 60000

app:
  # SQL/ORM/MEMORY
  access-type: ORM

provider:
  stackoverflow:
    base-url: https://api.stackexchange.com/2.3
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
  github:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN}
