server:
  port: 8081

spring:
  application:
    name: scrapper
  grpc:
    server:
      port: 9091

bot:
  transport: grpc

scheduler:
  interval: 60000

app:
  access-type: MEMORY # SQL/ORM/MEMORY

provider:
  stackoverflow:
    base-url: https://api.stackexchange.com/2.3
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
  github:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN}
