server:
  port: 8080

spring:
  application:
    name: bot
  messages:
    basename: "messages"
  grpc:
    server:
      port: 9090

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${APP_TELEGRAM_TOKEN}
    username: notification_tracker_robot
    update-listener-sleep: 1s
    debug: false

scrapper:
  transport: http

bot:
  messages:
    start-command:
      command: "/start"
      description: "Запустить бота"
    help-command:
      command: "/help"
      description: "Показать помощь"
    cancel-command:
      command: "/cancel"
      description: "Отменить"
    track-command:
      command: "/track"
      description: "Начать отслеживать ресурс"
    untrack-command:
      command: "/untrack"
      description: "Перестать отслеживать ресурс"
    list-command:
      command: "/list"
      description: "Получить отслеживаемые ресурсы"
