server:
  port: 8080

spring:
  application:
    name: bot
  messages:
    basename: "messages"
  grpc:
    server:
      port: 9090

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${APP_TELEGRAM_TOKEN}
    username: notification_tracker_robot
    update-listener-sleep: 1s
    debug: false

scrapper:
  transport: http
  http-url: http://scrapper:8081
  grpc-host: scrapper
  grpc-port: 9091


bot:
  tag-keyboard:
    max-buttons-before-input: 20
    max-visible-tags: 8
    tags-per-row: 3
    callback-prefix: "list_tag:"
    callback-show-all: "list_tags_all"
    callback-input: "list_tag_input"

  messages:
    start-command:
      command: "/start"
      description: "Запустить бота"
    help-command:
      command: "/help"
      description: "Показать помощь"
      aliases:
        - "❓ Помощь"
    cancel-command:
      command: "/cancel"
      description: "Отменить"
      aliases:
        - "❌ Отмена"
    track-command:
      command: "/track"
      description: "Начать отслеживать ресурс"
      aliases:
        - "➕ Добавить"
    untrack-command:
      command: "/untrack"
      description: "Перестать отслеживать ресурс"
      aliases:
        - "➖️ Убрать"
    list-command:
      command: "/list"
      description: "Получить отслеживаемые ресурсы"
      aliases:
        - "📋 Мои ссылки"
