server:
  port: 8080

spring:
  application:
    name: bot
  messages:
    basename: "messages"

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${APP_TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false


bot:
  messages:
    start-command:
      command: "/start"
      description: "Запустить бота"
    help-command:
      command: "/help"
      description: "Показать помощь"
    track-command:
      command: "/track"
      description: "Начать отслеживать ресурс"
