<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>backend.academy.link-tracker</groupId>
        <artifactId>parent</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>contracts</artifactId>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>

        <dependency>
            <groupId>org.instancio</groupId>
            <artifactId>instancio-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!--.proto gRPC generation-->
            <plugin>
                <groupId>io.github.ascopes</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!--            openapi generation-->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.10.0</version>
                <executions>
                    <!--                     генератор для контроллеров -->
                    <execution>
                        <id>generate-bot-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/bot-api.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <addCompileSourceRoot>true</addCompileSourceRoot>
                            <library>spring-boot</library>
                            <apiPackage>backend.academy.linktracker.bot.generated.api</apiPackage>
                            <modelPackage>backend.academy.linktracker.bot.generated.dto</modelPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useJakartaEe>true</useJakartaEe>
                                <skipDefaultInterface>true</skipDefaultInterface>
                            </configOptions>
                        </configuration>
                    </execution>

                    <execution>
                        <id>generate-scrapper-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/scrapper-api.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <addCompileSourceRoot>true</addCompileSourceRoot>
                            <library>spring-boot</library>
                            <apiPackage>backend.academy.linktracker.scrapper.generated.api</apiPackage>
                            <modelPackage>backend.academy.linktracker.scrapper.generated.dto</modelPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useJakartaEe>true</useJakartaEe>
                                <skipDefaultInterface>true</skipDefaultInterface>
                            </configOptions>
                        </configuration>
                    </execution>

                    <!--                    генератор для клиентов-->
                    <execution>
                        <id>generate-scrapper-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/scrapper-api.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <library>spring-http-interface</library>

                            <apiPackage>backend.academy.linktracker.scrapper.generated.client</apiPackage>
                            <modelPackage>backend.academy.linktracker.scrapper.generated.dto</modelPackage>
                            <generateSupportingFiles>false</generateSupportingFiles>

                            <importMappings>
                                <importMapping>AddLinkRequest=backend.academy.linktracker.scrapper.generated.dto.AddLinkRequest</importMapping>
                                <importMapping>ApiErrorResponse=backend.academy.linktracker.scrapper.generated.dto.ApiErrorResponse</importMapping>
                                <importMapping>LinkResponse=backend.academy.linktracker.scrapper.generated.dto.LinkResponse</importMapping>
                                <importMapping>ListLinksResponse=backend.academy.linktracker.scrapper.generated.dto.ListLinksResponse</importMapping>
                                <importMapping>RemoveLinkRequest=backend.academy.linktracker.scrapper.generated.dto.RemoveLinkRequest</importMapping>
                            </importMappings>

                            <schemaMappings>
                                <importMapping>AddLinkRequest=backend.academy.linktracker.scrapper.generated.dto.AddLinkRequest</importMapping>
                                <importMapping>ApiErrorResponse=backend.academy.linktracker.scrapper.generated.dto.ApiErrorResponse</importMapping>
                                <importMapping>LinkResponse=backend.academy.linktracker.scrapper.generated.dto.LinkResponse</importMapping>
                                <importMapping>ListLinksResponse=backend.academy.linktracker.scrapper.generated.dto.ListLinksResponse</importMapping>
                                <importMapping>RemoveLinkRequest=backend.academy.linktracker.scrapper.generated.dto.RemoveLinkRequest</importMapping>
                            </schemaMappings>

                            <configOptions>
                                <!--                                <interfaceOnly>true</interfaceOnly>-->
                                <!--                                <skipDefaultInterface>true</skipDefaultInterface>-->
                                <useJakartaEe>true</useJakartaEe>
                                <generateModels>true</generateModels>
                                <useRecords>true</useRecords>
                                <openApiNullable>false</openApiNullable>
                            </configOptions>
                        </configuration>
                    </execution>

                    <execution>
                        <id>generate-bot-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/bot-api.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <library>spring-http-interface</library>

                            <apiPackage>backend.academy.linktracker.bot.generated.client</apiPackage>
                            <modelPackage>backend.academy.linktracker.bot.generated.dto</modelPackage>
                            <generateSupportingFiles>false</generateSupportingFiles>

                            <importMappings>
                                <importMapping>ApiErrorResponse=backend.academy.linktracker.bot.generated.dto.ApiErrorResponse</importMapping>
                                <importMapping>LinkUpdate=backend.academy.linktracker.bot.generated.dto.LinkUpdate</importMapping>
                            </importMappings>

                            <schemaMappings>
                                <schemaMapping>ApiErrorResponse=backend.academy.linktracker.bot.generated.dto.ApiErrorResponse</schemaMapping>
                                <schemaMapping>LinkUpdate=backend.academy.linktracker.bot.generated.dto.LinkUpdate</schemaMapping>
                            </schemaMappings>

                            <configOptions>
                                <!--                                <interfaceOnly>true</interfaceOnly>-->
                                <!--                                <skipDefaultInterface>true</skipDefaultInterface>-->
                                <useJakartaEe>true</useJakartaEe>
                                <generateModels>true</generateModels>
                                <useRecords>true</useRecords>
                                <openApiNullable>false</openApiNullable>
                            </configOptions>
                        </configuration>
                    </execution>

                </executions>
            </plugin>
        </plugins>
    </build>

</project>
